pipeline {
    agent any
    stages {
        stage("Compile") {
            steps {
                // 이 라인을 추가하세요!
                sh 'chmod +x ./gradlew' 

                sh "./gradlew compileJava"
            }
        }
        stage("Build") {
            steps {
                sh "./gradlew build"
                sh 'chmod +x ./gradlew' 

            }
        }
        stage("Unit test") {
            steps {
                sh "./gradlew test"
            }
        }
    }
}